# Generated by Django 5.2.9 on 2026-10-02 17:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField(max_length=1000)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_sociais', to=settings.AUTH_USER_MODEL)),
                ('mencoes', models.ManyToManyField(blank=True, related_name='mencoes_em_comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'social_comentarios',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField(blank=True, max_length=2200)),
                ('midia', models.FileField(blank=True, null=True, upload_to='social/%Y/%m/')),
                ('tipo_midia', models.CharField(blank=True, choices=[('IMAGEM', 'Imagem'), ('VIDEO', 'Vídeo')], max_length=10)),
                ('formato', models.CharField(choices=[('POST', 'Post'), ('REEL', 'Reel')], default='POST', max_length=10)),
                ('visibilidade', models.CharField(choices=[('PUBLICO', 'Público'), ('AMIGOS', 'Só amigos')], default='PUBLICO', max_length=10)),
                ('eh_compartilhamento', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('compartilhado_de', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compartilhamentos', to='social.post')),
                ('mencoes', models.ManyToManyField(blank=True, related_name='mencoes_em_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'db_table': 'social_posts',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('CURTIDA', 'Curtida'), ('COMENTARIO', 'Comentário'), ('MENCAO', 'Menção'), ('COMPARTILHAMENTO', 'Compartilhamento'), ('AMIZADE_PEDIDO', 'Pedido de amizade'), ('AMIZADE_ACEITA', 'Amizade aceita')], max_length=20)),
                ('lida', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('ator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('comentario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='social.comentario')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='social.post')),
            ],
            options={
                'db_table': 'social_notificacoes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Curtida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curtidas', to='social.post')),
            ],
            options={
                'db_table': 'social_curtidas',
            },
        ),
        migrations.AddField(
            model_name='comentario',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='social.post'),
        ),
        migrations.CreateModel(
            name='Amizade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITA', 'Aceita')], default='PENDENTE', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('respondido_em', models.DateTimeField(blank=True, null=True)),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amizades_recebidas', to=settings.AUTH_USER_MODEL)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amizades_enviadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Amizade',
                'verbose_name_plural': 'Amizades',
                'db_table': 'social_amizades',
                'constraints': [models.UniqueConstraint(fields=('solicitante', 'destinatario'), name='amizade_unica'), models.CheckConstraint(condition=models.Q(('solicitante', models.F('destinatario')), _negated=True), name='amizade_nao_consigo')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-criado_em'], name='social_post_criado__7289a5_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['formato', '-criado_em'], name='social_post_formato_bfaa2c_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacao',
            index=models.Index(fields=['destinatario', 'lida'], name='social_noti_destina_5b87bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='curtida',
            constraint=models.UniqueConstraint(fields=('post', 'usuario'), name='curtida_unica'),
        ),
    ]
