# Generated by Django 5.2.9 on 2025-12-08 01:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
                'db_table': 'partidas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('valor_pontos', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prêmio',
                'verbose_name_plural': 'Prêmios',
                'db_table': 'premios',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('data_nascimento', models.DateField()),
                ('posicao', models.CharField(choices=[('GOLEIRO', 'Goleiro'), ('DEFENSOR', 'Defensor'), ('MEIA', 'Meia'), ('ATACANTE', 'Atacante')], max_length=20)),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to='perfis/')),
                ('auth_uid', models.CharField(max_length=255, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PremioPartida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios_recebidos', to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios_partida', to='rachas.partida')),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rachas.premio')),
            ],
            options={
                'verbose_name': 'Prêmio Partida',
                'verbose_name_plural': 'Prêmios Partidas',
                'db_table': 'premio_partida',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Racha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('imagem_perfil', models.ImageField(blank=True, null=True, upload_to='rachas/')),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('codigo_convite', models.CharField(editable=False, max_length=5, unique=True)),
                ('ponto_gol', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('ponto_assistencia', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('ponto_presenca', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rachas_administrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Racha',
                'verbose_name_plural': 'Rachas',
                'db_table': 'rachas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='premio',
            name='racha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='rachas.racha'),
        ),
        migrations.AddField(
            model_name='partida',
            name='racha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='rachas.racha'),
        ),
        migrations.CreateModel(
            name='RegistroPartida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('jogador_assistencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistencias_registradas', to=settings.AUTH_USER_MODEL)),
                ('jogador_gol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols_registrados', to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='rachas.partida')),
            ],
            options={
                'verbose_name': 'Registro Partida',
                'verbose_name_plural': 'Registros Partidas',
                'db_table': 'registro_partida',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='JogadorPartida',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('presente', models.BooleanField(default=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_partida', to=settings.AUTH_USER_MODEL)),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores_presenca', to='rachas.partida')),
            ],
            options={
                'verbose_name': 'Presença Jogador',
                'verbose_name_plural': 'Presenças Jogadores',
                'db_table': 'jogador_partida',
                'unique_together': {('partida', 'jogador')},
            },
        ),
        migrations.CreateModel(
            name='JogadoresRacha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rachas_participando', to=settings.AUTH_USER_MODEL)),
                ('racha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogadores_racha', to='rachas.racha')),
            ],
            options={
                'verbose_name': 'Jogador do Racha',
                'verbose_name_plural': 'Jogadores do Racha',
                'db_table': 'jogadores_racha',
                'unique_together': {('racha', 'jogador')},
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoRacha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ACEITO', 'Aceito'), ('NEGADO', 'Negado')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_racha', to=settings.AUTH_USER_MODEL)),
                ('racha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='rachas.racha')),
            ],
            options={
                'verbose_name': 'Solicitação Racha',
                'verbose_name_plural': 'Solicitações Rachas',
                'db_table': 'solicitacao_racha',
                'ordering': ['-criado_em'],
                'unique_together': {('racha', 'jogador')},
            },
        ),
    ]
