# Generated by Django 5.2.9 on 2025-12-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rachas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='posicao',
            field=models.CharField(choices=[('GOLEIRO', 'Goleiro'), ('ZAGUEIRO', 'Zagueiro'), ('LATERAL', 'Lateral'), ('VOLANTE', 'Volante'), ('MEIA', 'Meia'), ('ATACANTE', 'Atacante'), ('DEFENSOR', 'Defensor')], max_length=20),
        ),
    ]
