# Generated by Django 4.2.27 on 2025-12-08 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rachas', '0002_alter_user_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
