# Generated by Django 4.2.27 on 2025-12-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rachas', '0003_alter_user_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='racha',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='auth_uid',
            field=models.CharField(max_length=255),
        ),
    ]
