# Generated by Django 4.2.27 on 2025-12-09 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rachas', '0004_racha_descricao_alter_user_auth_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='partida',
            name='horario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='local',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partida',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
