# Generated by Django 4.2.27 on 2025-12-16 20:37

from django.conf import settings
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rachas', '0005_partida_horario_partida_local_partida_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='racha',
            name='administrador',
        ),
        migrations.AlterField(
            model_name='racha',
            name='ponto_assistencia',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='racha',
            name='ponto_gol',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='racha',
            name='ponto_presenca',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='racha',
            name='administrador',
            field=models.ManyToManyField(related_name='rachas_administrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
