# Generated by Django 4.2.27 on 2025-12-22 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rachas', '0006_remove_racha_administrador_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solicitacaoracha',
            unique_together={('racha', 'jogador', 'status')},
        ),
    ]
