# Generated by Django 4.2.27 on 2025-12-27 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rachas', '0007_alter_solicitacaoracha_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropartida',
            name='jogador_gol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gols_registrados', to=settings.AUTH_USER_MODEL),
        ),
    ]
