# Generated by Django 5.2.9 on 2026-10-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rachas', '0008_alter_registropartida_jogador_gol'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solicitacaoracha',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='solicitacaoracha',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'PENDENTE')), fields=('racha', 'jogador'), name='unica_solicitacao_pendente'),
        ),
    ]
