# Generated by Django 5.2.9 on 2026-10-02 14:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rachas', '0009_solicitacao_pendente_unica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('peso_bronze', models.PositiveIntegerField(default=60)),
                ('peso_prata', models.PositiveIntegerField(default=28)),
                ('peso_ouro', models.PositiveIntegerField(default=10)),
                ('peso_lenda', models.PositiveIntegerField(default=2)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('racha', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='rachas.racha')),
            ],
            options={
                'verbose_name': 'Álbum',
                'verbose_name_plural': 'Álbuns',
                'db_table': 'albuns',
            },
        ),
        migrations.CreateModel(
            name='EnvioPacotes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.CharField(blank=True, max_length=120)),
                ('pacotes_por_jogador', models.PositiveSmallIntegerField()),
                ('figurinhas_por_pacote', models.PositiveSmallIntegerField()),
                ('total_destinatarios', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='rachas.album')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Envio de Pacotes',
                'verbose_name_plural': 'Envios de Pacotes',
                'db_table': 'envios_pacotes',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Pacote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade_figurinhas', models.PositiveSmallIntegerField()),
                ('motivo', models.CharField(blank=True, max_length=120)),
                ('conteudo', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('aberto_em', models.DateTimeField(blank=True, null=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes', to='rachas.album')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacotes_figurinhas', to=settings.AUTH_USER_MODEL)),
                ('envio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacotes', to='rachas.enviopacotes')),
            ],
            options={
                'verbose_name': 'Pacote',
                'verbose_name_plural': 'Pacotes',
                'db_table': 'pacotes',
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='PaginaAlbum',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='rachas.album')),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas_album', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Página do Álbum',
                'verbose_name_plural': 'Páginas do Álbum',
                'db_table': 'paginas_album',
                'ordering': ['numero'],
                'unique_together': {('album', 'jogador')},
            },
        ),
        migrations.CreateModel(
            name='Figurinha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raridade', models.CharField(choices=[('BRONZE', 'Bronze'), ('PRATA', 'Prata'), ('OURO', 'Ouro'), ('LENDA', 'Lenda')], max_length=10)),
                ('numero', models.PositiveIntegerField()),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figurinhas', to='rachas.paginaalbum')),
            ],
            options={
                'verbose_name': 'Figurinha',
                'verbose_name_plural': 'Figurinhas',
                'db_table': 'figurinhas',
                'ordering': ['numero'],
                'unique_together': {('pagina', 'raridade')},
            },
        ),
        migrations.CreateModel(
            name='FigurinhaJogador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantidade', models.PositiveIntegerField(default=0)),
                ('colada', models.BooleanField(default=False)),
                ('obtida_em', models.DateTimeField(auto_now_add=True)),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figurinhas', to=settings.AUTH_USER_MODEL)),
                ('figurinha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colecoes', to='rachas.figurinha')),
            ],
            options={
                'verbose_name': 'Figurinha do Jogador',
                'verbose_name_plural': 'Figurinhas dos Jogadores',
                'db_table': 'figurinhas_jogador',
                'unique_together': {('dono', 'figurinha')},
            },
        ),
    ]
